version: '3.7'

services:
  db:
    container_name: db
    hostname: db
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: storage
    image: postgres
    restart: always
    networks:
      - backend

  minio:
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - storage:/data
    image: minio/minio:latest
    command: server --console-address ":9001" /data
    networks:
      - backend

  app:
    container_name: app
    image: cos7els/storage
    ports:
    - "8080:8080"
    depends_on:
      - db
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/storage
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      MINIO_ENDPOINT: http://minio:9000
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  storage: { }