version: '3.7'

services:
  db:
    container_name: db
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=storage
    image: postgres:latest
    networks:
      - backend

  s3:
    container_name: s3
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - storage:/data
    image: minio/minio:latest
    command: server --console-address ":9001" /data
    networks:
      - backend

  app:
    container_name: app
    image: storage:v2
    ports:
    - "8080:8080"
    environment:
     - DB_HOST=db
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  storage: {}