server:
  port: 8085

spring:
  application:
    name: subscription-service
  datasource:
    url: jdbc:postgresql://localhost:5432/subscriptiondb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  file:
    path: logs